// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

// Resolves the caller's identity from the gateway-injected header, common to
// every protected resource. A missing header means the request did not come
// through the gateway.
function resolveCallerId(string? x\-user\-id) returns string|ErrorUnauthorized {
    if x\-user\-id is string && x\-user\-id != "" {
        return x\-user\-id;
    }
    return <ErrorUnauthorized>{
        body: {code: 401, message: "unauthorized", description: "missing X-User-Id header"}
    };
}

service / on ep0 {
    # List the caller's own todos
    #
    # + x\-user\-id - caller identity injected by the gateway from the validated token
    # + completed - filter by completion state
    # + return - returns can be any of following types
    # http:Ok (matching todos)
    # http:Unauthorized (missing or invalid token)
    resource function get todos(@http:Header string? x\-user\-id, boolean? completed, int 'limit = 20, int offset = 0) returns TodoList|ErrorUnauthorized {
        string|ErrorUnauthorized caller = resolveCallerId(x\-user\-id);
        if caller is ErrorUnauthorized {
            return caller;
        }

        int effectiveLimit = 'limit;
        if effectiveLimit > 100 {
            effectiveLimit = 100;
        }
        if effectiveLimit < 1 {
            effectiveLimit = 20;
        }
        int effectiveOffset = offset < 0 ? 0 : offset;

        [Todo[], int]|error result = listTodosForUser(caller, effectiveLimit, effectiveOffset, completed);
        if result is error {
            log:printError("failed to list todos", 'error = result, userId = caller);
            return <ErrorUnauthorized>{body: {code: 401, message: "unauthorized"}};
        }

        [Todo[], int] [todos, count] = result;
        string? next = effectiveOffset + effectiveLimit < count
            ? buildPageUri(effectiveOffset + effectiveLimit, effectiveLimit, completed)
            : ();
        string? previous = effectiveOffset > 0
            ? buildPageUri(effectiveOffset - effectiveLimit < 0 ? 0 : effectiveOffset - effectiveLimit, effectiveLimit, completed)
            : ();

        return {count: count, next: next, previous: previous, data: todos};
    }

    # Mark the caller's own todo as complete
    #
    # + x\-user\-id - caller identity injected by the gateway from the validated token
    # + todoId - todo identifier
    # + return - returns can be any of following types
    # http:Ok (todo marked complete)
    # http:Unauthorized (missing or invalid token)
    # http:NotFound (todo not found or not owned by caller)
    resource function patch todos/[string todoId]/complete(@http:Header string? x\-user\-id) returns Todo|ErrorUnauthorized|ErrorNotFound {
        string|ErrorUnauthorized caller = resolveCallerId(x\-user\-id);
        if caller is ErrorUnauthorized {
            return caller;
        }

        Todo?|error result = completeTodoForUser(caller, todoId);
        if result is error {
            log:printError("failed to complete todo", 'error = result, userId = caller, todoId = todoId);
            return <ErrorNotFound>{body: {code: 404, message: "not found"}};
        }
        if result is () {
            return <ErrorNotFound>{
                body: {code: 404, message: "not found", description: "todo does not exist or is not owned by the caller"}
            };
        }
        return result;
    }

    # Create a new todo for the caller
    #
    # + x\-user\-id - caller identity injected by the gateway from the validated token
    # + return - returns can be any of following types
    # http:Created (todo created)
    # http:BadRequest (invalid todo payload)
    # http:Unauthorized (missing or invalid token)
    resource function post todos(@http:Header string? x\-user\-id, @http:Payload NewTodo payload) returns http:Created|ErrorBadRequest|ErrorUnauthorized {
        string|ErrorUnauthorized caller = resolveCallerId(x\-user\-id);
        if caller is ErrorUnauthorized {
            return caller;
        }

        string text = payload.text.trim();
        if text == "" {
            return <ErrorBadRequest>{
                body: {code: 400, message: "invalid todo payload", description: "text must not be empty"}
            };
        }

        Todo|error created = insertTodo(caller, text);
        if created is error {
            log:printError("failed to create todo", 'error = created, userId = caller);
            return <ErrorBadRequest>{body: {code: 400, message: "invalid todo payload"}};
        }
        return <http:Created>{body: created};
    }
}

function buildPageUri(int offset, int 'limit, boolean? completed) returns string {
    string uri = string `/todos?limit=${'limit}&offset=${offset}`;
    if completed is boolean {
        uri = uri + "&completed=" + completed.toString();
    }
    return uri;
}
