// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type Todo record {
    # todo identifier
    string id;
    # what needs to be done
    string text;
    # whether the todo is done
    boolean completed;
    # creation timestamp
    string createdAt;
};

public type NewTodo record {
    # what needs to be done
    string text;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TodoList record {
    # total matching todos
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
